spring.application.name=individual_project_programming3_chyhohidze_rufina
logging.level.root=info
logging.level.be.kdg.programming3=debug
spring.mvc.static-path-pattern=/static/**
spring.messages.basename=messages

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.sql.init.platform=h2
spring.h2.console.enabled=true