spring.application.name=individual_project_programming3_chyhohidze_rufina
logging.level.root=info
logging.level.be.kdg.programming3=debug
spring.mvc.static-path-pattern=/static/**
spring.messages.basename=messages

spring.profiles.active=jpa,post
# here you can change profile to an old(list) or new(h2), post(postgres), jpa(jpaData)

#ask chatgpt, to delete a row from intermidiate table before deleting the entity(doctor,patient)